#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    ignored='-I ".git" -I "node_modules" -I ".bloop" -I ".bsp" -I ".metals" -I ".scala-build" -I ".terraform" -I ".idea" -I "target" -I ".gradle"'
    selected=$(find ~/Cengage/RTA/Stash ~/NixEdu ~/.dotfiles -mindepth 0 -maxdepth 1 -type d ! -name '.git' \
        | fzf --preview "tree -a $ignored -C {} | head -200")
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux attach -d -t $selected_name
